### ISSUE TITLE
Mark required and optional fields in definitions

### ISSUE THREAD

**Issue by Richard-Degenne** [rain0r/listenbrainz-openapi#3]
Objects such as [`listensForUser`](components/core/listensForUser.yaml) do not define any `required` properties.

I'm currently developing a Ruby wrapper for the API and it's not clear what fields are always present and which one are optional. Adding this information to the documentation would be a great tool to ensure a good symmetry with the API typings.

# Example

```yaml
      listens:
        type: array
        items:
          type: object
          required: # <= Here
            - inserted_at
            - listened_at
            - track_metadata
          properties:
            inserted_at:
              type: integer
            listened_at:
              type: integer
            recording_msid:
              type: string
            track_metadata:
              $ref: '../common/trackMetadata.yaml'
            user_name:
              type: string
```
